# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true

extends:
  - 'airbnb-base'

rules:
    # Override default settings
    no-console: 0
    import/extensions: 0
